# Generated by Django 4.2.29 on 2026-03-16 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom_alertstreams', '0002_alert_flux'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='alert',
            name='tom_alertst_stream__a592d5_idx',
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['stream_name', 'topic', 'timestamp'], name='tom_alertst_stream__a32a9e_idx'),
        ),
    ]
