# Generated by Django 4.2.29 on 2026-06-05 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom_alertstreams', '0003_remove_alert_tom_alertst_stream__a592d5_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
    ]
