# Generated by Django 4.2.29 on 2026-06-09 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tom_alertstreams', '0004_alert_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['-created']},
        ),
    ]
