# Generated by Django 4.2.29 on 2026-06-09 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom_alertstreams', '0005_alter_alert_options'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='alert',
            name='tom_alertst_stream__a32a9e_idx',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='alert',
            name='observation_time',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='published_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['stream_name', 'topic', 'observation_time'], name='tom_alertst_stream__a16eaf_idx'),
        ),
    ]
